.ansible: &ansible
  stage: deploy
  image: gableroux/ansible:2.7.10
  before_script:
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh/
    - chmod 700 ~/.ssh
    - cat "$PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - cd ./ansible
    - chmod 600 $PRIVATE_KEY

stages:
    - deploy

staging:
    <<: *ansible
    stage: deploy
    tags: 
        - docker
    script:
        - ANSIBLE_CONFIG=./ansible.cfg /usr/local/bin/ansible-playbook deploy.yml --vault-password-file=$VAULT_KEY --key-file=$PRIVATE_KEY  -e env=staging -b -v
    only:
      - develop

production: 
    <<: *ansible
    stage: deploy
    tags: 
        - docker
    script:
        - ANSIBLE_CONFIG=./ansible.cfg /usr/local/bin/ansible-playbook deploy.yml --vault-password-file=$VAULT_KEY --key-file=$PRIVATE_KEY  -e env=production -b -v 
    only: 
      - master
    when: manual