export const MODAL_SIGNUP = 'MODAL_SIGNUP';
export const MODAL_SIGNIN = 'MODAL_SIGNIN';
export const MODAL_OFFER = 'MODAL_OFFER';
export const MODAL_NEWPARTNER = 'MODAL_NEWPARTNER';
export const MODAL_DELETECONFIRM = 'MODAL_DELETECONFIRM';
