export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOADING_PROGRESS = 'LOADING_PROGRESS';

export const MODAL_SIGNUP = 'MODAL_SIGNUP';
export const MODAL_SIGNIN = 'MODAL_SIGNIN';
export const MODAL_OFFER = 'MODAL_OFFER';

export const MODAL_NEWPARTNER = 'MODAL_NEWPARTNER';
export const MODAL_EDITPARTNER = 'MODAL_EDITPARTNER';
export const MODAL_NEWSERVICE = 'MODAL_NEWSERVICE';
export const MODAL_EDITSERVICE = 'MODAL_EDITSERVICE';

export const MODAL_DELETECONFIRM = 'MODAL_DELETECONFIRM';

export const COUNTRY_LIST = 'COUNTRY_LIST';
export const CATEGORY_LIST = 'CATEGORY_LIST';
export const SUBCATEGORY_LIST = 'SUBCATEGORY_LIST';
export const SERVICE_FILTER = 'SERVICE_FILTER';
